### PR TITLE
SOAP-539 Unable to validate some components

### PR DESCRIPTION
**Pull request by mc0918**
## Overview
[A recent issue occurred with SOAP](https://nuitadminsystems.atlassian.net/browse/SOAP-539) where applicants are unable to save/submit their applications due to the following error:
Screenshot (202)

Adding the null check in this PR seems to fix the issue, and I can view even multivalue directory search components that seem to be causing the problems.

Screenshot (204)

## Checklist

- [ ] `tests/` added or updated
- [ ] CHANGELOG.md's *Unreleased* section is updated
- [ ] Documentation is updated

### CODE REVIEW

**Comment by nie7321** [comment]
@mc0918 what component configuration can lead to this outcome?

Multiple values true but non-required?

**Comment by nie7321** [comment]
Instead of adding the null check when validating, I updated the `submissionValue()` implementation to handle that situation. Several of the components that implement their own `submissionValue()` methods already *had* better handling, so this seems like a better fix since consumers benefit from the more-reliable return type too.

How does it look, @mc0918?

**Comment by mc0918** [comment]
> Instead of adding the null check when validating, I updated the `submissionValue()` implementation to handle that situation. Several of the components that implement their own `submissionValue()` methods already _had_ better handling, so this seems like a better fix since consumers benefit from the more-reliable return type too.
> 
> How does it look, @mc0918?

Testing now! And to confirm on your earlier comment, yes, it looks like it's just text fields with multiple values but not required

**Comment by mc0918** [comment]
@nie7321 looks good! Thanks for the fix

**Pull request merged**
